//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public string SDT { get; set; }
        public string Avatar { get; set; }
        public string DiaChi { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
