//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHOI
    {
        public int ID { get; set; }
        public string CAUHOI1 { get; set; }
        public Nullable<int> ID_CAUTRL { get; set; }
        public string LOAICAUHOI { get; set; }
    }
}
